# Generated by Django 3.2.12 on 2023-08-14 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='ngaybatdau',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ngaysinh',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.CreateModel(
            name='diem',
            fields=[
                ('maxulydiem', models.AutoField(primary_key=True, serialize=False)),
                ('mucdatduoc', models.CharField(max_length=10)),
                ('diem', models.FloatField()),
                ('mahs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qldt_app.hocsinh')),
                ('mamonhoc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qldt_app.monhoc')),
            ],
        ),
    ]
